alias uw='ssh etham@linux.student.cs.uwaterloo.ca'
alias home='cd ~'
alias vi='vim'
alias grep='grep -E'
alias ls='ls -B --color=auto'
alias cache='cd ~/.cache/chromium/Default/Cache/'
alias cs241='cd ~/Documents/cs241/'
alias cs240='cd ~/Documents/cs240/'
alias cooldown='sudo sh -c "echo 5000 > /sys/devices/platform/applesmc.768/fan1_min"; sudo -k'
alias uncooldown='sudo sh -c "echo 2000> /sys/devices/platform/applesmc.768/fan1_min"; sudo -k'
